spring:
  application:
    name: sale-service
  datasource:
    url: jdbc:mysql://localhost:3306/springbootsecuirty
    password: root
    username: root
    tomcat:
      max-idle: 20
      max-wait: 20000
      max-active: 50
      min-idle: 15
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    service-url: http://localhost:8761

server:
  port: 8081
